Repository googleapis/python-datacatalog, pull requests merged in 2020-05, with the labels that each got.

#18 chore: Migrate python-datacatalog synth.py from artman to bazel
  synth.py
Labels: cla: yes

#20 feat: add `restricted_locations` to v1; add `order` to `TagField` and `TagTemplateField` in v1beta1; rename `field_path` to `tag_template_field_path` in v1beta1; add pagination support to `list_taxonomies` in v1beta1
  .kokoro/publish-docs.sh
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/datacatalog_v1/gapic/data_catalog_client.py
  google/cloud/datacatalog_v1/gapic/enums.py
  google/cloud/datacatalog_v1/gapic/transports/data_catalog_grpc_transport.py
  google/cloud/datacatalog_v1/proto/datacatalog_pb2.py
  google/cloud/datacatalog_v1/proto/datacatalog_pb2_grpc.py
  google/cloud/datacatalog_v1/proto/tags_pb2.py
  google/cloud/datacatalog_v1/proto/timestamps_pb2.py
  google/cloud/datacatalog_v1beta1/gapic/data_catalog_client.py
  google/cloud/datacatalog_v1beta1/gapic/data_catalog_client_config.py
  google/cloud/datacatalog_v1beta1/gapic/enums.py
  google/cloud/datacatalog_v1beta1/gapic/policy_tag_manager_client.py
  google/cloud/datacatalog_v1beta1/gapic/policy_tag_manager_serialization_client.py
  google/cloud/datacatalog_v1beta1/gapic/transports/data_catalog_grpc_transport.py
  google/cloud/datacatalog_v1beta1/proto/common_pb2.py
  google/cloud/datacatalog_v1beta1/proto/datacatalog_pb2.py
  google/cloud/datacatalog_v1beta1/proto/datacatalog_pb2_grpc.py
  google/cloud/datacatalog_v1beta1/proto/gcs_fileset_spec_pb2.py
  google/cloud/datacatalog_v1beta1/proto/policytagmanager_pb2.py
  google/cloud/datacatalog_v1beta1/proto/policytagmanagerserialization_pb2.py
  google/cloud/datacatalog_v1beta1/proto/schema_pb2.py
  google/cloud/datacatalog_v1beta1/proto/search_pb2.py
  google/cloud/datacatalog_v1beta1/proto/table_spec_pb2.py
  google/cloud/datacatalog_v1beta1/proto/tags_pb2.py
  google/cloud/datacatalog_v1beta1/proto/timestamps_pb2.py
  noxfile.py
  synth.metadata
  tests/unit/gapic/v1beta1/test_data_catalog_client_v1beta1.py
  tests/unit/gapic/v1beta1/test_policy_tag_manager_client_v1beta1.py
  tests/unit/gapic/v1beta1/test_policy_tag_manager_serialization_client_v1beta1.py
Labels: automerge, cla: yes

#25 feat: release as production/stable
  .repo-metadata.json
  README.rst
  setup.py
Labels: cla: yes

#31 chore(python): remove one remaining extra bash line (#565)
  .kokoro/release.sh
  synth.metadata
Labels: cla: yes, context: full

#30 chore: upgrade protoc-docs-plugin version to 0.7.0 to fix unstable docstrings.
  google/cloud/datacatalog_v1/proto/datacatalog_pb2.py
  google/cloud/datacatalog_v1/proto/gcs_fileset_spec_pb2.py
  google/cloud/datacatalog_v1/proto/schema_pb2.py
  google/cloud/datacatalog_v1/proto/search_pb2.py
  google/cloud/datacatalog_v1/proto/table_spec_pb2.py
  google/cloud/datacatalog_v1/proto/tags_pb2.py
  google/cloud/datacatalog_v1/proto/timestamps_pb2.py
  google/cloud/datacatalog_v1beta1/proto/datacatalog_pb2.py
  google/cloud/datacatalog_v1beta1/proto/gcs_fileset_spec_pb2.py
  google/cloud/datacatalog_v1beta1/proto/policytagmanager_pb2.py
  google/cloud/datacatalog_v1beta1/proto/policytagmanagerserialization_pb2.py
  google/cloud/datacatalog_v1beta1/proto/schema_pb2.py
  google/cloud/datacatalog_v1beta1/proto/search_pb2.py
  google/cloud/datacatalog_v1beta1/proto/table_spec_pb2.py
  google/cloud/datacatalog_v1beta1/proto/tags_pb2.py
  google/cloud/datacatalog_v1beta1/proto/timestamps_pb2.py
  synth.metadata
Labels: cla: yes, context: full
