Repository googleapis/python-datacatalog, pull requests merged in 2021-02, with the labels that each got.

#107 feat: add `client_cert_source_for_mtls` argument to transports
  google/cloud/datacatalog_v1/services/data_catalog/client.py
  google/cloud/datacatalog_v1/services/data_catalog/transports/grpc.py
  google/cloud/datacatalog_v1/services/data_catalog/transports/grpc_asyncio.py
  google/cloud/datacatalog_v1beta1/__init__.py
  google/cloud/datacatalog_v1beta1/services/data_catalog/client.py
  google/cloud/datacatalog_v1beta1/services/data_catalog/transports/grpc.py
  google/cloud/datacatalog_v1beta1/services/data_catalog/transports/grpc_asyncio.py
  google/cloud/datacatalog_v1beta1/services/policy_tag_manager/client.py
  google/cloud/datacatalog_v1beta1/services/policy_tag_manager/transports/grpc.py
  google/cloud/datacatalog_v1beta1/services/policy_tag_manager/transports/grpc_asyncio.py
  google/cloud/datacatalog_v1beta1/services/policy_tag_manager_serialization/client.py
  google/cloud/datacatalog_v1beta1/services/policy_tag_manager_serialization/transports/grpc.py
  google/cloud/datacatalog_v1beta1/services/policy_tag_manager_serialization/transports/grpc_asyncio.py
  synth.metadata
  tests/unit/gapic/datacatalog_v1/test_data_catalog.py
  tests/unit/gapic/datacatalog_v1beta1/test_data_catalog.py
  tests/unit/gapic/datacatalog_v1beta1/test_policy_tag_manager.py
  tests/unit/gapic/datacatalog_v1beta1/test_policy_tag_manager_serialization.py
Labels: api: datacatalog, automerge, cla: yes, context: partial

#104 test: update to latest configs
  .github/header-checker-lint.yml
  .trampolinerc
  noxfile.py
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#113 docs: fix `type_` attribute name in the migration guide
  UPGRADING.md
Labels: api: datacatalog, automerge, cla: yes

#114 docs: fix upgrade guide
  UPGRADING.md
Labels: api: datacatalog, automerge, cla: yes
