Repository googleapis/python-datacatalog, pull requests merged in 2021-12, with the labels that each got.

#268 docs: convert UPGRADING guide to RST to fix table formatting
  .github/.OwlBot.lock.yaml
  CHANGELOG.md
  UPGRADING.md
  UPGRADING.rst
  docs/UPGRADING.md
  docs/UPGRADING.rst
Labels: api: datacatalog, cla: yes

#274 chore: add api_shortname to repo-metadata.json
  .repo-metadata.json
Labels: api: datacatalog

#37 docs(samples): Add sample for PolicyTagManagerClient.create_taxonomy
  samples/snippets/conftest.py
  samples/snippets/data_catalog_ptm_create_taxonomy.py
  samples/snippets/data_catalog_ptm_create_taxonomy_test.py
Labels: api: datacatalog, cla: yes, samples
