Repository googleapis/python-datacatalog, pull requests merged in 2022-04, with the labels that each got.

#325 chore: set up CI on v0 branch
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  noxfile.py
Labels: api: datacatalog

#316 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v2 release
  noxfile.py
  setup.py
Labels: api: datacatalog

#318 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
  docs/conf.py
  google/cloud/datacatalog_v1/proto/datacatalog_pb2_grpc.py
  google/cloud/datacatalog_v1beta1/gapic/policy_tag_manager_client.py
  google/cloud/datacatalog_v1beta1/proto/datacatalog_pb2_grpc.py
  google/cloud/datacatalog_v1beta1/proto/policytagmanager_pb2_grpc.py
  google/cloud/datacatalog_v1beta1/proto/policytagmanagerserialization_pb2_grpc.py
  noxfile.py
  samples/v1beta1/datacatalog_get_entry.py
  samples/v1beta1/datacatalog_lookup_entry.py
  samples/v1beta1/datacatalog_lookup_entry_sql_resource.py
  samples/v1beta1/datacatalog_search.py
  setup.py
Labels: api: datacatalog, size: l

#326 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v0 release
  noxfile.py
  setup.py
Labels: api: datacatalog, size: xs
